FROM node:18.19.0-bullseye-slim

WORKDIR /home/pharmaplug_mobile/src

COPY frontend/pharmaplug-mobile/package.json frontend/pharmaplug-mobile/package-lock.json ./
RUN npm install

COPY frontend/pharmaplug-mobile .

EXPOSE 3000

CMD ["npm", "start"]