# Generated by Django 4.2 on 2024-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
