# Generated by Django 4.2 on 2024-12-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_html_content_transaction_object_ct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
    ]
